[orangu]
model = gemma-4-E4B-it-GGUF
timeout = 1800
max_tool_rounds = 10
# quotes = none
# width = 512
# banner = left
# feedback = off
# auto_rebase = off
# auto_squash = off
# terminal = xterm -e
# platform = github

[gemma-4-E4B-it-GGUF]
provider = llama.cpp
endpoint = http://localhost:8100/v1
model = ggml-org/gemma-4-E4B-it-GGUF

[Qwen3-Coder-30B-A3B-Instruct-GGUF]
provider = llama.cpp
endpoint = http://localhost:8100/v1
model = unsloth/Qwen3-Coder-30B-A3B-Instruct-GGUF
